# Generated by Django 3.0.5 on 2020-05-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='deliveryboyregister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('e_mail', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('mobilenumber', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='userregister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('e_mail', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('mobilenumber', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
    ]
