# Generated by Django 3.0.5 on 2020-06-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_breakfast_cooldrink_detergent_dryfruits_homecleaners_kitchencleaners_liquiddetergents_masalas_oils_r'),
    ]

    operations = [
        migrations.CreateModel(
            name='daycart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=10)),
                ('quantity', models.CharField(max_length=4)),
                ('price', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='monthlcart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=10)),
                ('quantity', models.CharField(max_length=4)),
                ('price', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='cooldrink',
            name='quantity',
            field=models.CharField(max_length=6),
        ),
    ]
