# Generated by Django 3.0.5 on 2020-06-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20200627_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('shopname', models.TextField(primary_key=True, serialize=False)),
                ('firstname', models.TextField()),
                ('e_mail', models.TextField()),
                ('mobilenumber', models.TextField()),
                ('password', models.TextField()),
                ('area', models.TextField()),
                ('city', models.TextField()),
            ],
        ),
    ]
