# Generated by Django 3.0.5 on 2020-07-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_setname'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegisterWithPK',
            fields=[
                ('firstname', models.TextField()),
                ('e_mail', models.TextField(primary_key=True, serialize=False)),
                ('mobilenumber', models.TextField()),
                ('password', models.TextField()),
                ('area', models.TextField()),
                ('city', models.TextField()),
            ],
        ),
    ]
