# Generated by Django 3.0.5 on 2020-07-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_userregisterwithpk'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDayCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.TextField()),
                ('productname', models.TextField()),
                ('brand', models.TextField()),
                ('quantity', models.TextField()),
                ('price', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usermonthlycart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.TextField()),
                ('productname', models.TextField()),
                ('brand', models.TextField()),
                ('quantity', models.TextField()),
                ('price', models.TextField()),
            ],
        ),
    ]
