# Generated by Django 3.0.5 on 2020-07-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_place_order_monthly'),
    ]

    operations = [
        migrations.CreateModel(
            name='deliverySide',
            fields=[
                ('customername', models.TextField(primary_key=True, serialize=False)),
                ('amount', models.TextField()),
            ],
        ),
    ]
